# Generated by Django 5.2 on 2025-05-07 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfeedback',
            name='choice',
            field=models.CharField(max_length=15),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
